#!/bin/bash

function print-data {

	COL1=date
	NCOL1=DATA
	COL2=order_for_place
	NCOL2=DIAS
	COL3=state
	NCOL3=UF
	COL4=city
	NCOL4=MUNICÍPIO
	COL5=last_available_confirmed
	NCOL5=No_DE_CASOS
	COL6=new_confirmed
	NCOL6=NOVOS_CASOS
	COL7=last_available_deaths
	NCOL7=No_DE_ÓBITOS
	COL8=new_deaths
	NCOL8=NOVOS_ÓBITOS
	COL9=last_available_death_rate
	NCOL9=MORTALIDADE
	COL10=estimated_population_2019
	NCOL10=POPULAÇÃO
	if [ -z "$1" ] 
	then
		echo -e "\nDigite um filtro ou pressione 'Enter' para obter a tabela completa"
		read -p "Filtrar por: " FILTER 
	else
		FILTER="$@"
	fi
	FILTER="$( echo "$FILTER" | sed "s/\s/_/g" )"
	sed "s/\s/_/g;s/,,/,---,/g;s/,/ /g;s/$COL1/$NCOL1/g;s/$COL2/$NCOL2/g;s/$COL3/$NCOL3/g;s/$COL4/$NCOL4/g;s/$COL5/$NCOL5/g;s/$COL6/$NCOL6/g;s/$COL7/$NCOL7/g;s/$COL8/$NCOL8/g;s/$COL9/$NCOL9/g;s/$COL10/$NCOL10/g" ""$HOME"/Downloads/covidbr" | grep -E -i -e "week" -e "\b$FILTER\b" | awk '{print $2, $3, $4, $5, $8, $10, $11, $12, $13, $14 }' | column -t | less

}

function update-data {

			DATE="$( date +"%d-%m-%Y %H:%M:%S" )"
			echo
			wget -O "$HOME/Downloads/covidbr" "https://brasil.io/dataset/covid19/caso_full/?place_type=city&format=csv"
			echo "$DATE" >> ""$HOME"/Downloads/covidbr"
}

echo -e "\nFonte: Barasil.io (https://brasil.io/)"
echo -e "O Brasil em dados libertos: Repositório de dados públicos disponibilizados em formato acessível"
echo -e "\nESPECIAL COVID-19 - Dados por Município"
echo -e "\nGraças a uma força-tarefa de 40 voluntários que, diariamente, compilam boletins epidemiológicos das 27 Secretarias Estaduais de Saúde, disponibilizamos uma base de dados com a série histórica de casos e óbitos confirmados por município. Embora essenciais para o planejamento de políticas de contenção do novo coronavírus, os dados municipais não têm sido divulgados pelo Ministério da Saúde. Ainda como parte desse esforço contínuo de fornecer dados úteis relacionados à pandemia, disponibilizamos outras bases estruturadas, como população dos municípios afetados, óbitos suspeitos registrados em cartório etc."

echo -e "\nURL: https://brasil.io/dataset/covid19/caso_full/?search=&epidemiological_week=&date=&order_for_place=&state=&city=&city_ibge_code=&place_type=city&last_available_date=&is_last=&is_repeated="
if [ -e ""$HOME"/Downloads/covidbr" ]
then
	echo -e "\nÚltima atualização: "$( tail -1 ""$HOME"/Downloads/covidbr" )""  
	echo -e "\nAtualizar base de dados?"
	read -p "[S] Sim [N] Não [A] Abortar (default: 'N'): " A 
	case "$A" in 
		[sS])
			update-data
			print-data "$@"
			
			;;
		[aA])
			clear
			;;
		*)
			print-data "$@"
			;;
	esac
else
	update-data
	print-data "$@"
fi
